# -*- coding: utf-8 -*-
"""2026_03_19_avaliacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNdb4zJ5HwNv74TX5PsclG_COttRmGKL
"""

#1. O Reflorestador (Loop com Acumulador)

'''
Em um mini-game de reflorestamento, o jogador deve plantar árvores até atingir
uma meta de "Biomassa". Crie um programa que peça ao usuário a meta de biomassa
 (em unidades). Depois, use um while para ler sucessivamente o valor de biomassa
 de cada árvore plantada. O programa deve parar assim que a meta for atingida ou
 superada e exibir quantas árvores foram necessárias.
'''

biomassa = int(input("Digite a meta de biomassa: "))
biomassa_arvore = 10
arvores = 0
biomassa_total = 0

while biomassa_total < biomassa:
  biomassa_total += biomassa_arvore
  arvores += 1
  print("Plantando árvore número ",arvores,"...")

print("Foi necessário plantar ",arvores, " árvore(s) para atingir a meta.")

#2. Simulador de Combate: Turnos de RPG
'''
Em um jogo de turno, um herói tem 100 de HP e enfrenta um monstro com 100 de HP.
O programa deve pedir ao usuário o dano do ataque do herói e o dano do ataque
do monstro por rodada. Use um while que continue enquanto ambos estiverem com HP
acima de zero. Ao final de cada turno, mostre o HP restante de ambos. Se alguém
chegar a 0, encerre e anuncie o vencedor.
'''

vida_heroi = 100
vida_monstro = 100

while vida_heroi > 0 and vida_monstro > 0:
  dano_heroi = int(input("Digite o dano do herói: "))
  dano_monstro = int(input("Digite o dano do monstro: "))
  vida_heroi -= dano_monstro
  vida_monstro -= dano_heroi
  print("Vida do herói: ",vida_heroi)
  print("Vida do monstro: ",vida_monstro)

if vida_heroi <= 0 and vida_monstro <= 0:
  print("Empate!")

elif vida_heroi <= 0:
  print("O monstro venceu!")

else:
  print("O herói venceu!")

#3. Monitor de Inundação (Sentinela)
'''
Você está desenvolvendo um sistema de alerta para uma Smart City. O programa
deve ler o nível do rio (em metros) continuamente.

* Se o nível for menor que 3m: "Estado Normal".
* Entre 3m e 5m: "Estado de Alerta".
* Acima de 5m: "Evacuação Imediata".
O programa só deve encerrar a leitura se o usuário digitar um valor negativo
(flag/bandeira de encerramento).
'''

nivel_rio = int(input("Digite o nível do rio ou um valor negativo para encerrar o programa: "))

while nivel_rio >= 0:
  if nivel_rio < 3:
    print("Estado Normal")
    nivel_rio = int(input("Digite o nível do rio ou um valor negativo para encerrar o programa: "))
  elif nivel_rio >= 3 and nivel_rio <= 5:
    print("Estado de Alerta")
    nivel_rio = int(input("Digite o nível do rio ou um valor negativo para encerrar o programa: "))
  else:
    print("Evacuação Imediata")
    nivel_rio = int(input("Digite o nível do rio ou um número negativo para encerrar o programa: "))

#4. O Coletor de Itens e Inventário
'''
Em um jogo de exploração, o jogador tem uma mochila com capacidade máxima de
15kg. Crie um programa que peça o peso de cada item encontrado no cenário, um
por um. O while deve permitir a entrada de itens enquanto o peso total não
ultrapassar 15kg. Se um item ultrapassar o limite, o programa deve avisar
"Mochila cheia, item descartado" e encerrar, mostrando o peso final total.
'''

carga_maxima = 15
peso_total = 0
inventario = ""

novo_item = input("Digite o item encontrado, seguindo o padrão 'nome,peso': ")

while peso_total < carga_maxima:
  nome,peso = novo_item.split(",")
  peso = float(peso)

  if peso + peso_total <= carga_maxima:
    inventario += "\n • " + nome
    peso_total += peso
  else:
    break

  print("\nInventário atual: ",inventario)
  print("Peso total: ",peso_total)

  novo_item = input("\nDigite o item encontrado, seguindo o padrão 'nome,peso': ")

print("\nMochila cheia, item descartado.")
print("\nInventário atual: ",inventario)
print("Peso total: ",peso_total)

#5. Média de Temperatura Global
'''
Para um painel informativo sobre mudanças climáticas, você precisa calcular a
média de temperatura de um período. O usuário deve informar quantos dias deseja
analisar. Use o while para ler a temperatura de cada um desses dias. Ao final,
o programa deve exibir a média aritmética das temperaturas e informar se a média
está "Acima do esperado" (caso seja maior que 25°C) ou "Dentro da normalidade".
'''

dias = int(input("Digite quantos dias deseja analisar: "))
dia_atual = 1
soma = 0

while dias > 0:
  temperatura = float(input("Digite a temperatura do dia "+ str(dia_atual)+ ": "))

  dias -= 1

  soma += temperatura

  if dias > 0:
    dia_atual += 1

media = soma / dia_atual

if media > 25:
  print("A média está acima do esperado. Calculada em ",media," graus.")
else:
  print("A média está dentro da normalidade. Calculada em ",media," graus.")