# -*- coding: utf-8 -*-
"""atividade_2026_05_28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVXta92dHACIqA3bzee3d68tnDyd9H-f
"""

'''
Trabalho: Sistema de Monitoramento Climático

Objetivo

Construir um programa em Python que leia uma lista de cidades, consulte as condições climáticas atuais de cada uma via API, armazene esses dados utilizando conceitos de Orientação a Objetos e exiba um relatório formatado na tela.

Requisitos do Sistema

1. Modelagem de Dados (Orientação a Objetos)

O aluno deve criar uma classe chamada CidadeClima.

Atributos privados/públicos: nome, temperatura, umidade e condicao.
Método Construtor (__init__): Para inicializar as propriedades.
Método de Exibição: Um método (ou sobrescrita do __str__) para retornar os dados formatados da cidade.

2. Consumo de Dados (API e Listas)

O programa deve possuir uma lista inicial com pelo menos 5 cidades pré-definidas (ex: ['São Paulo', 'London', 'Tokyo', 'New York', 'Paris']).
O sistema deve iterar sobre essa lista e fazer uma requisição HTTP (usando a biblioteca requests) para a API do OpenWeatherMap (OU A API TRABALHADA NA ÚLTIMA AULA) para cada cidade.
Os dados JSON retornados devem ser extraídos e instanciados como objetos da classe CidadeClima.
Cada objeto criado deve ser guardado em uma lista principal chamada relatorio_clima.

3. Exibição dos Resultados

O programa deve percorrer a lista relatorio_clima e exibir os dados na tela de forma organizada e legível para o usuário.

====================================
Critérios de Avaliação Sugeridos

Tratamento de Exceções: O aluno tratou possíveis erros de digitação de cidades ?
Uso Correto de OO: Os dados foram de fato transformados em objetos antes de irem para a lista, ou o aluno apenas manipulou dicionários diretamente na exibição?
Clean Code: Legibilidade de variáveis, indentação e comentários explicativos.
'''

#pip install install requests

import requests

class CidadeClima:
  #metodo construtor ou o instanciador de memória
  def __init__(self, nome, temp=None, temp_max=None, temp_min=None, condicao=None, umidade=None, vento=None):
    self.nome = nome
    self.temp = temp
    self.temp_max = temp_max
    self.temp_min = temp_min
    self.condicao = condicao
    self.umidade = umidade
    self.vento = vento

  # Função para buscar o clima de uma cidade
  def pegar_clima(self, api_key):
    # URL da API do OpenWeatherMap com o parâmetro 'q' para cidade e 'appid' para chave de API
    url = f"http://api.openweathermap.org/data/2.5/weather?q={self.nome},GBP&appid={api_key}&units=metric&lang=pt_br"

    # Enviar a requisição GET
    resposta = requests.get(url)

    # Verificar se a requisição foi bem-sucedida
    if resposta.status_code == 200:
        dados = resposta.json()

        # Extrair os dados relevantes e atribuir aos atributos da instância
        main = dados['main']
        weather = dados['weather'][0]
        wind = dados['wind']

        self.temp = main['temp']
        self.temp_min = main['temp_min']
        self.temp_max = main['temp_max']
        self.condicao = weather['description'].capitalize()
        self.umidade = main['humidity']
        self.vento = wind['speed']
        return True
    else:
        print(f"Erro ao obter dados para {self.nome}: {resposta.status_code}")
        return False

  def __str__(self):
    if self.temp is not None:
        return f'Cidade: {self.nome.capitalize()}\nTemperatura: {self.temp}°C \nTemperatura Máxima: {self.temp_max}°C \nTemperatura Mínima: {self.temp_min}°C \nCondição: {self.condicao.capitalize()} \nUmidade: {self.umidade}% \nVelocidade do Vento: {self.vento} m/s'
    else:
        return f'Cidade: {self.nome.capitalize()}, Dados climáticos não disponíveis.'

if __name__ == "__main__":
    # API do OpenWeatherMap
    api_key = '57f02dc11685a9611b42a5a22012380c'

relatorio_cidade = []

cidades_nomes = ['São Paulo', 'London', 'Tokyo', 'New York', 'Paris']

# Create CidadeClima objects for each city name
for nome_cidade in cidades_nomes:
  cidade_obj = CidadeClima(nome_cidade)
  relatorio_cidade.append(cidade_obj)

#Buscar o clima para as cidades
for cidade_obj in relatorio_cidade:
  cidade_obj.pegar_clima(api_key)

for cidade in relatorio_cidade:
  print(cidade)
  print('-' * 25)