# -*- coding: utf-8 -*-
"""atividade_2026_04_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMB5rMztW3H72EbFq_GO-pe0othokdUG
"""

# tarefa avaliativa
# lista e decomposição funcional
# Criar un programa com método que popule N numeros aleatórios (0 a 10) em uma lista. Também crie método que exiba a lista.
# O método a ser criado para avaliacao, nao pode ter pacotes, bibliotecas ou funcoes prontas do Python.
# O método deve receber uma lista com números e retirar (da propria lista) todos os numeros replicados.
# Por exemplo, lista inicial = [6,4,2,6,9,2,6]
# lista transformada = [6,4,2,9]

import random

def popular_lista(lista, quantidade):
  for i in range(quantidade):
    lista.append(random.randint(1, 10))

def exibir_lista(lista):
  for item in lista:
    print(item)

def retira_numeros_repetidos(lista_numeros):
  lista_sem_repetidos = []
  for numero in lista_numeros:
    if numero not in lista_sem_repetidos:
      lista_sem_repetidos.append(numero)
  return lista_sem_repetidos

lista_numeros = []

popular_lista(lista_numeros, 10)

exibir_lista(lista_numeros)

lista_numeros = retira_numeros_repetidos(lista_numeros)

exibir_lista(lista_numeros)