# -*- coding: utf-8 -*-
"""atividade_2026_05_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2G8qZ8FAzXNshRtB4w_H4UFhAKX5qmz
"""

'''
Analisador de Desempenho: "Arena dos Campeões"

Contexto:
Dado um arquivo .txt que simula o log de uma partida de um jogo de RPG/Combate.
Cada linha do arquivo representa as estatísticas finais de um jogador
no seguinte formato:

NomeDoJogador; Classe; Kills; Deaths; DanoCausado

Exemplo do arquivo partida.txt

Aragorn;Guerreiro;15;2;4500
Legolas;Arqueiro;22;1;5200
Gandalf;Mago;10;5;8000
Frodo;Ladrão;1;10;500
Gimli;Guerreiro;12;4;3800
Boromir;Guerreiro;8;8;2500
Galadriel;Mago;5;0;9500
Eowyn;Guerreiro;11;3;4100
Faramir;Arqueiro;9;4;3200
Saruman;Mago;18;2;8800
Sauron;Mago;30;1;15000
Gollum;Ladrão;2;15;300
Sam;Ladrão;4;2;1200
Merry;Ladrão;3;4;800
Pippin;Ladrão;2;5;700
Elrond;Mago;7;1;6000
Arwen;Mago;4;0;4500
Theoden;Guerreiro;10;6;3500
Ugluk;Guerreiro;6;12;2000
Lurtz;Arqueiro;14;5;4800

Desafio:
Desenvolver um programa Python que processe esses dados e gere um relatório
de performance.

Requisitos do Código:
* Leitura e Tratamento: Criar uma função para ler o arquivo e retornar uma
lista de dicionários (AINDA NÃO TRABALHADO EM SALA, MAS ENTRA COMO DESAFÍO),
convertendo valores numéricos para int.

Exemplo... o dicionário da linha Aragorn;Guerreiro;15;2;4500 ficaria

{
    "nome": "Aragorn",
    "classe": "Guerreiro",
    "kills": 15,
    "deaths": 2,
    "dano": 4500
}
Continuando o exemplo em código Python ...

# Lista que armazenará todos os dicionários
jogadores = []

# Exemplo de processamento dentro do loop de leitura
linha = "Aragorn;Guerreiro;15;2;4500"
dados = linha.strip().split(";")

# Cria o dicionário do jogador atual
jogador = {
    "nome": dados[0],
    "classe": dados[1],
    "kills": int(dados[2]),
    "deaths": int(dados[3]),
    "dano": int(dados[4])
}

# Adiciona o dicionário na lista principal
jogadores.append(jogador)

* Cálculo de KDA: Criar uma função que receba o número de Kills e Deaths
e retorne o KDA (Kills divided by Deaths). Dica: Tratar divisão por zero.

* Filtragem por Classe: Criar uma função que receba a lista tratada
e o nome de uma classe (ex: "Mago") e retorne apenas os jogadores dessa categoria.

* Destaques da Partida: Identificar e imprimir:
     - O jogador que causou o maior dano.
     - A média de kills da partida.
     - O nome dos jogadores com KDA superior a 2.0, formatados em letras maiúsculas.
'''

#iniciando variáveis
jogadores = [] #iniciando lista de jogadores
jogadores_dicio = [] #iniciando lista de dicionários

#função para leitura e tratamento do txt
def ler_txt(caminho_arquivo):
  #abrindo o txt
  with open(caminho_arquivo) as arquivo:
    conteudo = arquivo.read(); #lendo o txt e armazenando numa variável

  jogadores = conteudo.splitlines() #criando a lista dividindo o texto linha por linha

  #separando dados de cada linha da lista de jogadores
  for jogador in jogadores:
    dados = jogador.split(";")

    #cria o dicionário do jogador atual
    jogador_dicio = {
      "nome": dados[0],
      "classe": dados[1],
      "kills": int(dados[2]),
      "deaths": int(dados[3]),
      "dano": int(dados[4])
    }

    #adicionando dados separados em uma nova lista
    jogadores_dicio.append(jogador_dicio)

#função para calcular KDA
def calcula_KDA(kills, deaths):
  if deaths == 0: #tratando divisão por 0
    return kills
  else:
    return kills / deaths #retornando KDA

#função para filtrar classes
def filtra_classe(jogadores, classe):
  jogadores_filtrados = []
  for jogador in jogadores:
    if jogador["classe"] == classe:
      jogadores_filtrados.append(jogador)
  return jogadores_filtrados #retornando jogadores da classe escolhida

#função para encontrar jogador com maior dano da partida
def jogador_maior_dano(jogadores):
  maior_dano = 0
  jogador_maior_dano = ""
  for jogador in jogadores:
    if jogador["dano"] > maior_dano:
      maior_dano = jogador["dano"]
      jogador_maior_dano = jogador["nome"]
  return jogador_maior_dano #retornando jogador encontrado

#função para calcular média de kills da partida
def media_kills(jogadores):
  total_kills = 0
  for jogador in jogadores:
    total_kills += jogador["kills"]
  return total_kills / len(jogadores) #retornando média

#função para encontrar jogadores com KDA > 2.0
def jogadores_alto_KDA(jogadores):
  jogadores_alto_KDA = []
  for jogador in jogadores:
    if jogador["kills"] > 2.0:
      #armazenando nome dos jogadores em maiúsculas
      jogadores_alto_KDA.append(jogador["nome"].upper())
  return jogadores_alto_KDA #retornando jogadores com KDA > 2.0

#lendo e tratando arquivo
ler_txt("/content/partida.txt")

#filtrando classes
texto = input("Digite uma classe para filtrar jogadores (Arqueiro, Guerreiro, Ladrão ou Mago): ")

#se o texto digitado não for uma classe válida
if(texto != "Arqueiro" and texto != "Guerreiro" and texto != "Ladrão" and texto != "Mago"):
  print("Classe inválida!") #digo que é uma classe inválida
#se é uma classe válida
else:
  #uso a função para dizer os jogadores da clsse escolhida
  print(f"JOGADORES DA CLASSE {texto.upper()}:")

  for jogador in filtra_classe(jogadores_dicio, texto):
    print(jogador["nome"])

#DESTAQUES DA PARTIDA
print("DESTAQUES DA PARTIDA\n")
print(f"JOGADOR COM MAIOR DANO: {jogador_maior_dano(jogadores_dicio)}\n")
print(f"MÉDIA DE KILLS DA PARTIDA: {media_kills(jogadores_dicio)}\n")
print(f"JOGADORES COM KDA > 2.0:")
for jogador in jogadores_alto_KDA(jogadores_dicio):
  print(jogador)