# -*- coding: utf-8 -*-
"""aula_2026_03_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKa4eTahaOdz_L_VTCJC6C9ZT5DKYw8d

**Estudo de estrutura de um programa Python**

- Ambientes de edição e de desenvolvimento
  - PyCharm
  - VSCode
  - Colab
- Instruções Básicas
  - Leitura (input)
  - Escrita na tela (print)
  - Atribuição (=)
- Instruções de Seleção
  - if-else
  - if-elif
- Instruções de Repetição
  - for
  - while
"""

#Implementando restrições
data_invalida = True

while (data_invalida):
  data_invalida = False

  data = input("Digite uma data: ")
  dia, mes, ano = data.split("/")
  dia = int(dia)
  mes = int(mes)
  ano = int(ano)

  if dia < 1 or dia > 31:
    print("Data inválida com dia inválido.")
    data_invalida = True

  if mes < 1 or mes > 12:
    print("Data inválida com mês inválido.")
    data_invalida = True

  if ano < 1900 or ano > 2025:
    print("Data inválida com ano inválido.")
    data_invalida = True

while(True):
  cpf = input("Digite o CPF: ")

  if len(cpf) != 11:
    print("CPF inválido.")
    break

while(True):
  nome_completo = input("Digite seu nome completo: ")
  palavras_nome = nome_completo.split(" ")

  if len(palavras_nome) >= 2:
    print("Seu nome completo é: ", nome_completo)
    print("Seu nome é: ", palavras_nome[0])
    print("Seu sobrenome é: ", palavras_nome[-1])
    print("Seu nome tem ", len(palavras_nome), " palavras.")
    break

  print("Nome inválido.")

while(True):
  nome_completo = input("Digite seu nome completo: ")
  palavras_nome = nome_completo.split(" ")

  if len(palavras_nome) >= 2:
    primeiro = palavras_nome[0].lower()
    sobrenome = palavras_nome[-1].lower()
    email = primeiro + "." + sobrenome + "@ufn.edu.br"
    print("Seu email criado é: ", email)
    break

  print("Nome inválido.")

frase = input("Digite uma frase: ")
print("A frase tem ", len(frase), " caracteres.")
print("A frase original: ",frase)
print("A frase em MAIÚSCULO: ",frase.upper())
print("A frase em minúsculo: ",frase.lower())

#Trocar "a" por "@" e "e" por "&"
'''
for letra in frase:
  if letra == "a":
    letra = "@"
  elif letra == "e":
    letra = "&"
'''

nova_frase = frase.replace("a","@")
nova_frase = nova_frase.replace("e","&")

print("A frase com '@' no lugar de 'a' e '&' no lugar de 'e' é: ", nova_frase)