# -*- coding: utf-8 -*-
"""aula 2026 04 23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMyil7yxLraNcX3z5sQECidX2ABsHdtp

Organização dos dados


*   arquivo texto (csv) com
palavras ou expressões pejorativas
*   lista para armazenar as palavras ou expressões pejorativas
*   variável texto (digitada pelo usuário)

Fluxo ou dinâmica do sistema

1) executar o sistema em terminal (Command Line Interface)

2) carregar as palavras pejorativas do arquivo para dentro da lista

3) receber texto do usuário

4) analisar se as palavras do texto aparecem na lista de palavras pejorativas

5) mostrar as palavras do texto que estão na lista, bem como a quantidade delas

lista_palavras = [amor, coquinho, docinho]

texto = 'hoje eu acordei e fui trabalhar de moto.'

lista_texto = [hoje, eu, acordei, e, fui, trabalhar, de, moto, .]

palavras_pejorativas = [corno, safado, bagaceiro, maroto]
"""

with open("/content/palavras_negativas.csv") as arquivo:
  conteudo = arquivo.read();

lista_palavras_negativas = []

#criando a lista dividindo o texto linha por linha
lista_palavras_negativas = conteudo.splitlines()

#ordenando a lista
lista_palavras_negativas.sort()

#mostrando a quantidade de palavras/expressões na lista
print(len(lista_palavras_negativas))

print(lista_palavras_negativas)

texto = input("Digite um texto para a análise: ")
lista_texto = []
lista_texto = texto.split()
print(lista_texto)

for palavra_negativa in lista_palavras_negativas:
  ocorrencias = 0
  for palavra_texto in lista_texto:
    if palavra_negativa == palavra_texto:
      ocorrencias += 1

  if ocorrencias > 0:
    print(f"A palavra {palavra_negativa} foi encontrada {ocorrencias} vez(es).")