# -*- coding: utf-8 -*-
"""aula_2026_04_09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4z7JHUTAca-JK6_11ArUJ_kgqZ0kSqy

LISTAS
"""

import random

lista_numeros = []
lista_nomes = []

lista_numeros.append(5) #Para adicionar valores manualmente
lista_numeros.append(3)
lista_numeros.append(1)

print(lista_numeros)

for i in range(5): #Para adicionar valores automaticamente
  numero_sorteado = random.randint(0,100)
  lista_numeros.append(numero_sorteado)

print(lista_numeros)

lista_numeros.sort() #Para ordenar

print(lista_numeros)

#Pesquisando um valor
numero_pesquisa = int(input("Digite um número para pesquisar na lista: "))

if(numero_pesquisa in lista_numeros):
  print("O número está na lista.")
else:
  print("O número não está na lista.")

#Removendo um valor
numero_pesquisa = int(input("Digite um número para remover da lista: "))

if(numero_pesquisa in lista_numeros):
  lista_numeros.remove(numero_pesquisa)
  print("O número foi removido.")
else:
  print("O número não está na lista.")

print(lista_numeros)

#Calculando a média
soma = 0

for numero in lista_numeros:
  soma += numero

media = soma / len(lista_numeros)

print("A média dos valores da lista é: ", media)

#Encontrando o menor e o maior valor

lista_numeros.sort() #Para ordenar

print("O menor valor da lista é: ", lista_numeros[0])
print("O maior valor da lista é: ", lista_numeros[len(lista_numeros)-1])

#Apagando todos os valores pares

print(lista_numeros)

i = 0

while(i < len(lista_numeros)-1):
  if(lista_numeros[i] % 2 == 0):
    lista_numeros.remove(lista_numeros[i])
    i -= 1
  i += 1

print(lista_numeros)

#Apagando os valores repetidos (ex.: [1,1,2,3,4,4,5,5,5,5,6] -> [1,2,3,4,5,6])

print(lista_numeros)

i = 0

lista_numeros.sort()

while(i < len(lista_numeros)-1):
  if(lista_numeros[i] == lista_numeros[i+1]):
    lista_numeros.remove(lista_numeros[i])
    i -= 1
  i += 1

print(lista_numeros);