# -*- coding: utf-8 -*-
"""aula_2026_04_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185wdT9WiSW5WgGZBYPtio9gflk2s5AkX

LISTAS E FUNÇÕES
"""

#listas -> conjunto de dados organizados (ordenados), que recebem as operações: append, remove, in, empty, len

import random

#metodo em forma de função ou procedimento
def popular_lista(lista, quantidade):
  for i in range(quantidade):
    lista.append(random.randint(1, 100))

#método em forma de fun~ção ou procedimento
def exibir_lista(lista):
  for item in lista:
    print(item)


def copiar_numeros(lista_numeros, lista_pares, lista_impares):
  for numero in lista_numeros:
    if numero % 2 == 0:
      lista_pares.append(numero)
    else:
      lista_impares.append(numero)

lista_numeros_aleatorios = []
lista_pares = []
lista_impares = []

#acionando (invocando) um método que tem o serviço de popular uma lista com n números
#ao utilizarmos métodos, estamos usando DECOMPOSIÇÃO FUNCIONAL
popular_lista(lista_numeros_aleatorios, 10)

copiar_numeros(lista_numeros_aleatorios, lista_pares, lista_impares)

print("Números pares:")
exibir_lista(lista_pares)
print("\n")

print("Números ímpares:")
exibir_lista(lista_impares)
print("\n")

import random

def sortear_valores_inflacao(lista, quantidade):
  for i in range(quantidade):
    lista.append(random.randint(4,10))

def exibir_dados_inflacao(lista):
  for item in lista:
    print(item)

def calcular_min(lista):
  menor = lista[0]
  mes = 0

  for item in range(len(lista)):
    if lista[item] < menor:
      menor = lista[item]
      mes = item

  return menor, mes + 1

def calcular_max(lista):
  maior = lista[0]
  mes = 0

  for item in range(len(lista)):
    if lista[item] > maior:
      maior = lista[item]
      mes = item

  return maior, mes + 1

#simulando que 0 é janeiro, 1 é fevereiro, 2 é março, assim por diante
lista_inflacao = []

sortear_valores_inflacao(lista_inflacao, 12)
exibir_dados_inflacao(lista_inflacao)

meses = ["", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]

valor_minimo, mes_minimo = calcular_min(lista_inflacao)
valor_maximo, mes_maximo = calcular_max(lista_inflacao)

print(f"Valor mínimo é {valor_minimo} no mês {meses[mes_minimo]}.")
print(f"Valor máximo é {valor_maximo} no mês {meses[mes_maximo]}.")

#print(f"Valor máximo: {calcular_max(lista_inflacao)}")