# -*- coding: utf-8 -*-
"""aula_2026_02_26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfev-Obh8zufNIUcaWt8F3oWOHTM6RRt

**Python como linguagem de programação:**

- Linguagem interpretada
- Linguagem não tipada
- Categorias de Instruções
  - Instruções Primitivas
    - Item da lista
    - Item da lista
- Item da lista
- Item da lista

**Mostrando mensagens (print)**
"""

print("Olá pessoal.")
print("Primeira aula de programação prática.")

"""**Pegando valores pelo teclado (input) e convertendo variáveis**"""

nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
anos_dormidos = int(idade / 3)
print("Olá ", nome,", você já dormiu ", anos_dormidos, " anos!")

frase = "Turma de Python."
print(frase)

frase = 9876
print(frase)

nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))

if idade >= 18:
  print("Você é maior de idade.")
else:
  print("Você é menor de idade.")

'''
Receber o nome de um aluno
Receber a nota do primeiro bimestre
Receber a nota do segundo bimestre
Receber a nota do terceiro bimestre
Receber a nota do quarto bimestre
Calcular a média dos bimestres e informar se o aluno está:
  Aprovado (média >= 7)
  Recuperação (média >= 5 e média < 7)
  Reprovado (média < 5)
'''

nome = input("Digite seu nome: ")
nota1 = float(input("Digite a nota do primeiro bimestre: "))
nota2 = float(input("Digite a nota do segundo bimestre: "))
nota3 = float(input("Digite a nota do terceiro bimestre: "))
nota4 = float(input("Digite a nota do quarto bimestre: "))

media = (nota1 + nota2 + nota3 + nota4) / 4

if(media >= 7):
  resultado = "foi Aprovado."
elif(media >= 5):
  resultado = "está em Recuperação."
else:
  resultado = "foi Reprovado."

print(nome, resultado)
print("Média: ", media)

'''
Receber o nome de um paciente
Receber a idade do paciente
Receber o peso do paciente
Receber a altura do paciente
Calcular o IMC = peso (altura * altura)
Imprimir o nome, a idade e o IMC do paciente
'''

nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
peso = float(input("Digite seu peso (kg): "))
altura = float(input("Digite sua altura (m): "))

imc = peso / (altura * altura)

print("O IMC de", nome, ", que tem",idade,"anos, é", round(imc, 2), ".")

'''
Receber o nome de um funcionário
O valor base de hora de trabalho
A quantidade de horas trabalhadas por semana
Calcular o salário do funcionário = valor base da hora * quantidade de horas trabalhadas
Calcular quantos anos o funcionário está na empresa
Se estiver entre 4 e 8 anos, adicionar 4% ao salário
Se estiver entre 8 e 12 anos, adicionar 6% ao salário
Se estiver acima de 12 anos, adicionar 8% ao salário
Ao final, exibir o salário do funcionário
'''

nome = input("Digite o nome do funcionário: ")
base = float(input("Digite o valor base da hora de trabalho (R$): "))
horas = float(input("Digite a quantidade de horas trabalhadas por semana: "))
tempo = float(input("Digite há quantos anos o funcionário trabalha na empresa: "))

salario = base * horas

if(tempo > 4 and tempo <= 8):
  salario = salario * 1.04
if(tempo > 8 and tempo <= 12):
  salario = salario * 1.06
if(tempo > 12):
  salario = salario * 1.08

print("O salário de", nome, "é R$", round(salario, 2), ".")

'''
Fazer um programa que receba um a sigla de um estado brasileiro
Enquanto a sigla digitada não for válida, o programa deve solicitar novamente ao usuário
'''

estados = ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"]

teste = input("Digite a sigla do Estado (somente letras maiúsculas): ")

for estado in estados:
  if teste == estado:
    print("Você digitou ", estado)
    break
  else:
    print("Tente novamente.")
    teste = input("Digite a sigla do Estado (somente letras maiúsculas): ")

    #while not in